### ISSUE TITLE
Arguments of DCG_at_k function.

### ISSUE THREAD

**Issue by Vishruth-Sham** [yaochenzhu/Deep-Deconf#3]
https://github.com/yaochenzhu/Deep-Deconf/blob/29ac843576ca95e212e863e8d5085fbfbf5f28cb/data_sim/libs/evaluate.py#L98

Shouldn't the arguments be DCG_at_k(y_true,y_pred,k) instead of y_true,y_true

**Comment by Vishruth-Sham** [comment]
the code seems to be right

**Comment by yaochenzhu** [comment]
I don't think so. This is the normalizer.
